[project]
name = "5daygenai"
version = "0.1.0"
description = "ARM-only version"
readme = "README.md"
requires-python = ">=3.12,<3.13"

dependencies = [
    "beir",
    "numpy",
    "torch; platform_machine == 'arm64'",
    "faiss-cpu; platform_machine == 'arm64'",
    "google-cloud-aiplatform[vertexai]>=1.132.0",
]
